(in-package :prml.chapter1)

(defun fig1-12 ()
  (let* ((x (vgplot:range -101/100 101/100 1/100))
         (y (map 'vector #'(lambda (xn) (+ (gaussian-distribution 0.2 (expt 0.15 2) xn)
                                           (gaussian-distribution 0.7 (expt 0.1 2) xn)))
                 x))
         (y2 (make-array (1- (length x)))))
    (setf (aref y2 0) (* 1/100 (/ (+ (aref y 0) (aref y 1)) 2)))
    (loop :for i :from 1 :below (1- (length x))
          :do (setf (aref y2 i) (+ (aref y2 (1- i))
                                   (* 1/100 (/ (+ (aref y i) (aref y (1+ i))) 2)))))
    (setf y2 (map 'vector #'(lambda (y2n) (* 2 y2n)) y2))
    (vgplot:plot x y "r;"
                 x y2 "b;")
    (vgplot:grid nil)
    (vgplot:format-plot nil "unset xtics")
    (vgplot:format-plot nil "unset ytics")
    (vgplot:text 0.85 3.8 "P(x)" :tag 1)
    (vgplot:text 0.6 3.7 "p(x)" :tag 2)
    (vgplot:xlabel "x")
    (vgplot:axis '(0 1))))
