(in-package :prml.chapter1)

(defun fig1-2 ()
  (let* ((sin-x (vgplot:range 0 101/100 1/100))
         (sin-y (map 'vector #'(lambda (x) (sin (* 2 pi x))) sin-x))
         (traingin-set (vgplot:load-data-file (asdf:system-relative-pathname :prml "data/data.csv")))
         (observed-x (first traingin-set))
         (observed-y (second traingin-set)))
    (vgplot:plot sin-x sin-y "g;"
                 observed-x observed-y "ob;")
    (vgplot:axis '(-0.1 1.1 -1.5 1.5))
    (vgplot:grid nil)
    (vgplot:format-plot nil "set xtics 1")
    (vgplot:format-plot nil "set ytics 1")
    (vgplot:xlabel "x")
    (vgplot:ylabel "t")))
